### PR TITLE
feat: update colors & add some hover effects for the isometric icon

### PR DESCRIPTION
**Pull request by AKindWorld**
Also tried to add group-hover effects (hovering over a group changes fill colors of child elements of neighboring groups), but my current (uncommitted) approach in SCSS doesn't work. Probably since they are child elements of the parents' siblings and can't be accessed by CSS?

Also colors are not final (except for 001), let me know if I should change any of them to make it look better. 004, 005, and 006 are the previously existing ones.

Please feel free to suggest changes and guide me, thanks!

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Heey, i am a bit busy this week. Can i get back to you after 5-6 days.

Congratulations on your path as a web-dev.

**Comment by AKindWorld** [comment]
yup, definitely. Thanks a lot.

In the meantime, I will redesign some parts a lil bit, or change a few more stuff in this PR (also edit the branch name). Please let me know later if I'm doing it correctly.

**Comment by baseplate-admin** [comment]
> on further thought (a.k.a. a long long thinking session between my last two braincells), I have no idea what to rename the branch name to. As always, I'm just plain bad at naming. I should just go ahead and name them with the name of my favorite charas, uh-huh.

I usually name my branch `test`, `a` or anything. I do not think that branch name matters.

Tattoo on the other hand is a bit pragmatic regarding this.

Cc : @moonlitgrace

**Comment by moonlitgrace** [comment]
hi @AKindWorld good to see you here!
> I'm just plain bad at naming. I should just go ahead and name them with the name of my favorite charas, uh-huh.

well @baseplate-admin already spoiled github standards of this repo so it actually doesnt matter, you can name it as you wish.
but i like following git naming conventions unlike him :\ you can refer [this blog](https://medium.com/@abhay.pixolo/naming-conventions-for-git-branches-a-cheatsheet-8549feca2534) if you wann check it out.

> Also colors are not final (except for 001), let me know if I should change any of them to make it look better. 004, 005, and 006 are the previously existing ones.

uh is it necessary to modify tailwind config? i mean we can make it local to that component by defining in `<style` tag. or
instead hard coding shades of `primary` color, we can use [chroma.js](https://gka.github.io/chroma.js/), [fffuel.co](https://www.fffuel.co/iiisometric/) uses it for creating this shades.

image

i believe we can get shades of `primary` color and assign each to a style variable and use it on elements with `peer-hover` or using scss, this might need some svelte side things, can you give it a shot titan?
well that was just my thinking, lmk if you need any help.

what do you think @baseplate-admin

**Comment by baseplate-admin** [comment]
> what do you think @baseplate-admin

Tooo complex :(

---

> Can i get back to you after 5-6 days?

**Comment by AKindWorld** [comment]
heyaa @moonlitgrace 

> you can refer [this blog](https://medium.com/@abhay.pixolo/naming-conventions-for-git-branches-a-cheatsheet-8549feca2534) if you wann check it out.

thanks a lot, this was very helpful.

> uh is it necessary to modify tailwind config? i mean we can make it local to that component by defining in <style tag.

oops, sorry. I will try specifying the colors locally instead. was kinda an oversight on my part.

> i believe we can get shades of primary color and assign each to a style variable and use it on elements with peer-hover or using scss, this might need some svelte side things, can you give it a shot titan?

this kinda went over my head, but I think you meant using varying shades of colors on hovering over sibling elements? or did you mean it as the solution to the svg hover problem I faced earlier? (the one below)

> Also tried to add group-hover effects (hovering over a group changes fill colors of child elements of neighboring groups), but my current (uncommitted) approach in SCSS doesn't work. Probably since they are child elements of the parents' siblings and can't be accessed by CSS?

sorry for my low knowledge regarding these stuff and thanks for your insights ^^

---

also side question, is Vercel auto-deploy paused for PRs in this project, or do I need to mark it as ready for review for it to start deploying the commits?

**Comment by baseplate-admin** [comment]
> also side question, is Vercel auto-deploy paused for PRs in this project, or do I need to mark it as ready for review for it to start deploying the commits?

Uh unfortunately, we dont have vercel. Vercel for organisations is paid

**Comment by moonlitgrace** [comment]
hey @AKindWorld, love this PR.
thank you :heart:

**Review by moonlitgrace — APPROVED** [review]
hey @AKindWorld, love this PR.
thank you :heart:

**Pull request merged**
